### ISSUE TITLE
Add Multi Touch Gestures

### ISSUE THREAD

**Issue by marbetschar** [elementary/switchboard-plug-pantheon-shell#199] opened 2020-01-13 15:06 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature

It would be awesome to have Multi Touch Gestures on Pantheon Desktop - a feature I really fell in love with on macOS: https://support.apple.com/en-us/HT204895

To begin with, the most used two gestures in my personal experience are: Multi-Finger-Horizontal-Swipe to change Workspace (left or right), and Multi-Finger-Upwards-Swipe to show all Windows of the current Workspace (aka. "Multitasking View" = `Super + Arrow-Down`). Whereas "Multi-Finger' is defined as "More-Than-Two-Fingers".

**UPDATE:** Here's a link showing how this might be done: http://ubuntu-snippets.blogspot.com/2009/03/multi-touch-for-anyall-synaptics.html

**Comment by danrabbit** [comment] 2020-01-13 16:38
Gonna close as a duplicate of https://github.com/elementary/switchboard-plug-mouse-touchpad/pull/44

**Closed by danrabbit** 2020-01-13 16:38 UTC
