### ISSUE TITLE
Problem With Main Settings

### ISSUE THREAD

**Issue by Loway-MT** [elementary/switchboard-plug-pantheon-shell#197] opened 2019-12-31 05:36 UTC
When I Press The ShutDown Or Restart Buttons
Nothing Happens

**Comment by danrabbit** [comment] 2020-01-02 17:32
OP can you clarify a little bit? Are you referring to physical buttons on your computer or buttons in the shutdown dialog or some other interface?

**Comment by cassidyjames** [comment] 2020-01-10 18:22
Unless I hear otherwise, I presume this is a duplicate of https://github.com/elementary/wingpanel-indicator-session/issues/97

**Closed by cassidyjames** 2020-01-10 18:22 UTC
Labels: Status: Incomplete
