### ISSUE TITLE
problem with set-wallpaper contract

### ISSUE THREAD

**Issue by danahynes** [elementary/switchboard-plug-pantheon-shell#277] opened 2021-05-29 00:12 UTC
Hi!

I'm writing a script that changes the wallpaper. If I run '/usr/lib/x86_64-linux-gnu/io.elementary.contract.set-wallpaper' as root or sudo, the program tries to delete all the files in the current directory. I've found the problem in :
"switchboard-plug-pantheon-shell/set-wallpaper-contract/set-wallpaper.vala"
at line 144:
string greeter_data_dir = Path.build_filename (Environment.get_variable ("XDG_GREETER_DATA_DIR"), "wallpaper");
When run as root or sudo, the environment value "XDG_GREETER_DATA_DIR" does not exist, so the value seems to default to the current directory. I've added checks in my program both to ensure it is not run as root or sudo, and also the make sure the env variable exists and is not empty. Perhaps this kind of check could be added to your app? This would only affect users that have not set up a root user and therefore don't have a greeter dir.

I know most people won't try to run set-wallpaper as root or sudo, but for me it is called from another script that DOES run as sudo, and it caused me a lot of headaches. I've since found a workaround, but it just seems like a one or two line change could prevent these headaches for others. 

Thanks!

**Comment by lorencinibrdev** [comment] 2021-09-03 20:02
Looks like a duplicate of #262 ?

**Closed** 2022-08-11 04:03 UTC
