### ISSUE TITLE
Degraded font

### ISSUE THREAD

**Issue by genseirin** [elementary/switchboard-plug-pantheon-shell#430] opened 2024-12-11 17:25 UTC
### What Happened?

On some windows, most text is degraded when the window is in focus.

![Bildschirmfoto von 2024-12-11 18 09 58](https://github.com/user-attachments/assets/0ec51b66-41a3-4133-b545-2f2f13533dbf)

### Steps to Reproduce

First seen on the welcome screen after installation, then often again without any clear regularity.

### Expected Behavior

The text should be legible.

### OS Version

8.x (Circe)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Hardware Info

MacBook Pro
Intel Core i7-3520M CPU @ 2.90GHz
Intel HD Graphics 4000
8 GB RAM
750 GB storage

**Comment by ryonakano** [comment] 2024-12-30 10:32
Duplicate of elementary/triage#651

**Closed by ryonakano** 2024-12-30 10:32 UTC

**Comment by genseirin** [comment] 2024-12-30 11:00
Additional information: I used Ubuntu Budgie (24.x) on the same machine without any issues regard text rendering. In Elementary the appearance sometimes changed depending on the focus of the window or whether text was selected. It could be an issue that appears only for a certain font style.
