### ISSUE TITLE
Desktop Suggestions - Top System Taskbar

### ISSUE THREAD

**Issue by aliceemanueli** [elementary/switchboard-plug-pantheon-shell#292] opened 2021-09-14 11:24 UTC
the top system bar could have in "system setup" the option to "smart stop hiding" when an app is full screen the bar is hidden to give more screen space!  I think it would be a nice option in the system settings.  Thank you!

**Comment by lenemter** [comment] 2022-08-11 04:14
I think this is a duplicate of elementary/wingpanel#53

**Closed by lenemter** 2022-08-11 04:14 UTC
