### ISSUE TITLE
Apps using the default style do not change to Dark appearances

### ISSUE THREAD

**Issue by doamatto** [elementary/switchboard-plug-pantheon-shell#285] opened 2021-08-11 00:33 UTC
## What Happened
When using Flatpak apps (namely Ghostwriter, LibreWolf) and .DEB apps (namely 1Password), these apps do not use the default theme, despite them being set to such. On other distributions, this is a non-issue, which leads me to think this would be a problem with Elementary, rather than these apps. 

## Expected Behavior
Apps, when set to do so, should be using the theme set in Elementary OS.

## Steps to Reproduce
1. Change the Styling in Elementary's system settings to Dark
2. Open an app that supports system theming (eg. Firefox or an aforementioned)
3. Note how the theming does not change to the system default

## Platform Information
Elementary OS 6
LibreWolf 90.0.2
ghostwriter 1.8.0
1Password 8.1.2-82.BETA

Intel i7-8565U
UHD 620 + GeForce MX150
16,0 GiB memory

**Comment by danrabbit** [comment] 2021-08-11 17:37
Hey thanks for your issue report! In elementary OS the dark style is opt-in, which means developers have to choose to support it. Some other distros may force a dark style, but we don't do this to avoid breaking apps with custom styles.

Closing as "out of scope" since the dark style is working as intended and app developers need to choose to support it

**Closed by danrabbit** 2021-08-11 17:37 UTC

**Comment by m93a** [comment] 2021-08-12 01:18
If I manually add the following into `~/.config/gtk-3.0/settings.ini`, many GTK apps will be in dark mode by default:
```ini
[Settings]
gtk-application-prefer-dark-theme=1
```
This makes a big difference for example in `gnome-system-monitor`. Wouldn't it be possible for elementary to write the current state of dark mode into `gtk-3.0/settings.ini`, so that it would be cross-compatible with standard GTK apps?

**Comment by doamatto** [comment] 2021-08-19 14:11
This would be what I mean by the expected behaviour; it doesn't make much sense to me to have only apps that choice-in to Elementary's system to be the only ones to have theme switching, when most every other distro edits the GTK settings to prefer a dark theme. I agree with m93a that there should be that cross-compatibility with the mass of GTK apps, not just choiced-in ones.
