### ISSUE TITLE
Hot corner isn't disabled during gaming

### ISSUE THREAD

**Issue by TulparBey** [elementary/switchboard-plug-pantheon-shell#412] opened 2024-07-20 16:57 UTC
### What Happened?

As the title implies during gaming hot corner ought be disabled. No matter what I did in the settings, I couldn't disable it.  Either system should react to it by disabling and re-enabling hot corners afterwards or there should be a short cut to do so.

### Steps to Reproduce

Opened a game and hot corner was still active. I believe full screen apps should also be included.

### Expected Behavior

Not getting overview when I move my mouse inside a game.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
unrelated.
```

### Hardware Info

unrelated. But if needed I will share it.

**Comment by danirabbit** [comment] 2024-07-20 19:03
Hey thanks for your issue report. This is a actually a duplicate of https://github.com/elementary/gala/issues/1648

The issue was fixed recently and we have a new setting for this in the upcoming OS 8 release

**Closed by danirabbit** 2024-07-20 19:03 UTC

**Comment by TulparBey** [comment] 2024-07-20 19:11
> Hey thanks for your issue report. This is a actually a duplicate of [elementary/gala#1648](https://github.com/elementary/gala/issues/1648)
> 
> The issue was fixed recently and we have a new setting for this in the upcoming OS 8 release

Sorry, I did take a look at the previous bugs before filing this but it seems I missed it. Glad to hear it's fixed tho. Keep up the good work, can't wait for the new release
