### ISSUE TITLE
Wallpapers appearance gets randomly switched

### ISSUE THREAD

**Issue by DanyGee** [elementary/switchboard-plug-pantheon-shell#154] opened 2018-11-02 21:04 UTC
Sometimes wallpapers appear from **default -> latest**...
![screenshot from 2018-11-02 21 43 00 2x](https://user-images.githubusercontent.com/26818551/47940386-bc707400-deea-11e8-82d6-4aa4fc058536.png)
...and sometimes from **latest -> default**...
![screenshot from 2018-11-02 21 58 34 2x](https://user-images.githubusercontent.com/26818551/47940445-e45fd780-deea-11e8-8e6c-89467c63891b.png)
Don't know what triggers it.
Appears to be random.
Not a big deal, but shows some system inconsistency.

:desktop_computer: 
```
System:    Host: elementary-os Kernel: 4.15.0-38-generic x86_64 bits: 64 gcc: 7.3.0
           Desktop: Gnome  (Gtk 3.22.30) Distro: elementary OS 5.0 Juno
Machine:   Device: desktop Mobo: ASUSTeK model: Z170-DELUXE v: Rev 1.xx serial: N/A
           UEFI [Legacy]: American Megatrends v: 3504 date: 06/29/2017
CPU:       Quad core Intel Core i7-6700K (-MT-MCP-) arch: Skylake-S rev.3 cache: 8192 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 32064
           clock speeds: max: 4300 MHz 1: 1156 MHz 2: 3838 MHz 3: 3420 MHz 4: 3981 MHz 5: 3960 MHz 6: 3754 MHz
           7: 3722 MHz 8: 3417 MHz
Graphics:  Card: NVIDIA GP104 [GeForce GTX 1080] bus-ID: 01:00.0
           Display Server: x11 (X.Org 1.19.6 ) driver: nvidia Resolution: 3840x2160@60.00hz
           OpenGL: renderer: GeForce GTX 1080/PCIe/SSE2 version: 4.6.0 NVIDIA 390.77 Direct Render: Yes
Audio:     Card-1 NVIDIA GP104 High Definition Audio Controller driver: snd_hda_intel bus-ID: 01:00.1
           Card-2 Intel Sunrise Point-H HD Audio driver: snd_hda_intel bus-ID: 00:1f.3
           Card-3 Creative Live! Cam Chat HD [VF0700] driver: USB Audio usb-ID: 001-002
           Sound: Advanced Linux Sound Architecture v: k4.15.0-38-generic
Network:   Card-1: Intel Ethernet Connection (2) I219-V driver: e1000e v: 3.2.6-k bus-ID: 00:1f.6
           IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter>
           Card-2: Broadcom Limited BCM4360 802.11ac Wireless Network Adapter
           driver: bcma-pci-bridge bus-ID: 07:00.0
           IF: N/A state: N/A mac: N/A
           Card-3: Intel I211 Gigabit Network Connection driver: igb v: 5.4.0-k port: c000 bus-ID: 0b:00.0
           IF: enp11s0 state: down mac: <filter>
Drives:    HDD Total Size: 2570.6GB (2.6% used)
           ID-1: /dev/sda model: Samsung_SSD_850 size: 256.1GB
           ID-2: /dev/sdc model: Crucial_CT1050MX size: 1050.2GB
           ID-3: /dev/sdb model: Samsung_SSD_850 size: 1024.2GB
           ID-4: /dev/sdd model: KINGSTON_SH100S3 size: 120.0GB
           ID-5: /dev/sde model: KINGSTON_SV300S3 size: 120.0GB
Partition: ID-1: / size: 110G used: 63G (61%) fs: ext4 dev: /dev/sde1
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 33.0C mobo: N/A gpu: 0.0:54C
           Fan Speeds (in rpm): cpu: 0
Info:      Processes: 281 Uptime: 40 min Memory: 3958.2/32101.8MB Init: systemd runlevel: 5 Gcc sys: 7.3.0
           Client: Shell (bash 4.4.191) inxi: 2.3.56 
```

**Comment by peteruithoven** [comment] 2019-02-08 10:47
Thanks for the report! I'm afraid this is a duplicate of #109

**Closed by peteruithoven** 2019-02-08 10:47 UTC
