### ISSUE TITLE
Apply Dark Mode To Uncurated (Flatpak) Apps

### ISSUE THREAD

**Issue by jhaygood86** [elementary/switchboard-plug-pantheon-shell#249] opened 2020-10-24 02:59 UTC
## Problem

Currently, Dark Mode only applies to Curated elementary apps. However, there are many apps, especially in flathub, that use Adwaita due to not opting into the elementary stylesheet. Effectively, these apps completely are unaware of the Dark Mode setting.

## Proposal
Have flatpak set the theme for non-curated apps to Adwaita:dark instead of Adwaita, potentially only if an option is applied "Apply to non-curated flatpak applications". elementary aware apps would still use the elementary stylesheet and the dark mode setting switch.

## Prior Art
GNOME and macOS both apply the Dark Mode to all apps. Since elementary apps **should** be aware of opting into Dark Mode specifically, I think this is mostly for non-curated apps that aren't aware of the elementary dark mode setting. These apps are already using Adwaita today, so they aren't getting a fully integrated experience to begin with.

**Comment by danrabbit** [comment] 2020-10-24 04:10
The dark style preference is purposefully opt-in. All major platforms including Android, iOS, the web, etc operate on an opt-in basis for dark style adoption. This ensures that the app actually supports running in a dark style and avoids style breakage. We are trying to work with the larger freedesktop ecosystem to create a common opt-in dark style preference that more apps will support.

But, by design we intentional will not force a dark style on apps that do not opt-in. So this is a "won't fix" from that perspective.

**Closed by danrabbit** 2020-10-24 04:11 UTC

**Comment by cassidyjames** [comment] 2020-10-24 05:03
For more context, we're currently working on getting the setting mirrored as a GSetting so it's easy for GNOME and Flatpak apps to opt in. We hope to align on a GSetting/API with GNOME so this will improve in the future. We have to do that anyway for even elementary Flatpaked apps to work correctly.

**Comment by jhaygood86** [comment] 2020-10-24 06:48
My understanding is that major desktop systems, macOS, require apps to opt out of dark mode: https://developer.apple.com/documentation/xcode/supporting_dark_mode_in_your_interface

GNOME is the same way: adopting Adwaita Dark for instance switches all app

Android 10 is the same way: it's opt out unless using a custom theme and then it's opt in. I just re-read the documentation and confirmed that again.

My thinking this was more for third party non-native (flathub for instance) apps who are completely unaware and don't explicitly support elementary (and probably never will) and already using Adwaita. Adwaita default looks contrastingly bad against elementary dark, so if the plan is to use Adwaita for these apps.
