### ISSUE TITLE
Systemcolor resets to yellow when changing AM/PM to 24-hour (and vice versa)

### ISSUE THREAD

**Issue by Larse99** [elementary/switchboard-plug-pantheon-shell#271] opened 2021-05-02 20:47 UTC
Hi,

Title ^

Basically when setting a systemcolor to for example green and then going into time and date settings and change AM/PM to 24-hour, the systemcolor resets to yellow.

**Comment by lenemter** [comment] 2023-04-05 10:16
Closing because cannot reproduce in OS 7.

**Closed by lenemter** 2023-04-05 10:16 UTC
