### ISSUE TITLE
ModeButtons (style schedule, text size) not selectable with keyboard

### ISSUE THREAD

**Issue by mcclurgm** [elementary/switchboard-plug-pantheon-shell#278] opened 2021-06-05 01:19 UTC
## What Happened

I am unable to select either of the ModeButton sets in the Appearance panel with the keyboard. I can click on them or tab around, but in both cases the focus skips over them. The only selectable items seem to be the style modes, accent color, dyslexia font switch, and back button.

## Expected Behavior

Both button sets should be selectable by keyboard.

## Steps to Reproduce

1. Select the currently active theme radio button (you can use the left/right arrow keys to demonstrate this)
2. Press tab to select the next widget
3. Focus will move to the accent color (you can use the left/right arrow keys to demonstrate this)
4. Continue tabbing around: the only widgets that select are the ones I stated. Eventually, you will cycle back to the style selector without ever selecting the ModeButtons.

### Logs

n/a

## Platform Information

Odin daily, up to date as of 6/4/21

**Comment by jeremypw** [comment] 2021-06-05 09:27
Widgets need to have the "can-focus" property set in order to get keyboard focus.

**Comment by mcclurgm** [comment] 2021-06-05 16:15
Is it a bug that that property is missing from these buttons? I imagine I could make a PR to fix that fairly quickly if desired.

**Comment by jeremypw** [comment] 2021-06-05 16:30
Looks like it is a deficiency in the Granite implementation of this widget - keyboard operation is not implemented so there is no point in focusing it :disappointed:  Files implements keyboard shortcuts to allow keyboard selection of view modes but not sure that is practical everywhere.

**Comment by mcclurgm** [comment] 2021-06-05 16:32
Oh, got it. I'll open up a new issue in Granite then.

**Comment by danrabbit** [comment] 2021-06-08 18:51
I can confirm this is an issue in Granite. Closing here

**Closed by danrabbit** 2021-06-08 18:51 UTC
